#include "bmp_loader.h"
#include <stdio.h>

/******************************************************************************
 * Main part: load data, invoke processing routine, save data.
 *****************************************************************************/

Retcode BmpRead(const char* filename,
    BmpFormat format,
    struct BmpHeader* out_hdr,
    uint8_t* data,
    size_t data_size)
{
    Retcode rc = RC_FAILED;
    FILE* fin = NULL;

    fin = fopen(filename, "rb");
    CHECK(NULL != fin);

    CHECK(1 == fread(out_hdr, sizeof(struct BmpHeader), 1, fin));
	/* We only support v4 bitmaps as generated by GIMP on Linux */
	CHECK(SZ_BMP_HEADER_V4 == out_hdr->imageStartOffset);
	CHECK(0 == fseek(fin, out_hdr->imageStartOffset, SEEK_SET));
    CHECK(1 == fread(data, data_size, 1, fin));

    rc = RC_OK;
fail:
    if (fin) {
        fclose(fin);
    }
    return rc;
}

Retcode BmpWrite(const char* filename,
    BmpFormat format,
    struct BmpHeader header,
    uint8_t* data,
    size_t data_size)
{
    Retcode rc = RC_FAILED;
    FILE* fout = NULL;

    fout = fopen(filename, "wb");
    CHECK(NULL != fout);

    CHECK(1 == fwrite(&header, sizeof(struct BmpHeader), 1, fout));
	CHECK(0 == fseek(fout, header.imageStartOffset, SEEK_SET));
    CHECK(1 == fwrite(data, data_size, 1, fout));

    rc = RC_OK;
fail:
    if (fout) {
        fclose(fout);
    }

    return rc;
}
